language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnotify-bin
before_script:
  - bower install
  - npm install -g gulp
script: gulp